# Generated by Django 3.2.8 on 2021-10-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='username',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='user_id',
        ),
        migrations.AddField(
            model_name='delivery',
            name='notes',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
