# Generated by Django 3.2.8 on 2021-10-27 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211027_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
