# Generated by Django 3.2.8 on 2021-10-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211008_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiration_date',
            field=models.CharField(help_text='00/00', max_length=5),
        ),
    ]
