# Generated by Django 3.2.8 on 2021-10-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20211013_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
