# Generated by Django 3.2.8 on 2021-10-15 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_payment_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
